os: osx
language: objective-c
osx_image: xcode8.3
env:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FRAMEWORK_NAME="MATRIX Utils"
before_install:
  - gem install xcpretty -N
script: ./ci/travis.sh