os: osx
language: objective-c
osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="MATRIX Utils"
before_install:
  - rvm install ruby-2.2.2
  - gem install xcpretty -N
script: ./ci/travis.sh